# Generated by Django 2.0 on 2018-02-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('kind', models.CharField(choices=[('S', 'single'), ('D', 'double')], max_length=1)),
                ('duration', models.CharField(choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '60 minute')], max_length=2)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Masseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('surname', models.CharField(max_length=35)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('phone', models.PositiveIntegerField()),
                ('massages', models.ManyToManyField(to='massage.Massage')),
            ],
        ),
    ]
