# Generated by Django 2.0 on 2018-02-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0003_auto_20180207_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='favorites',
            field=models.ManyToManyField(to='massage.Masseur'),
        ),
    ]
