# Generated by Django 2.0 on 2018-02-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0004_client_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=1)),
                ('masseur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='massage.Masseur')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='massage.Masseur'),
        ),
    ]
