# Generated by Django 2.0 on 2018-02-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0005_auto_20180208_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='masseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='massage.Masseur'),
        ),
    ]
