# Generated by Django 2.0 on 2018-02-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0007_auto_20180208_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='massage.Client')),
                ('massage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='massage.Massage')),
                ('masseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='massage.Masseur')),
            ],
        ),
    ]
